### PR TITLE
WIP: Category name appearing in code list form and using accept_nested_att…

### PR DESCRIPTION
**Pull request by simonreed**
…ributes for code_lists #160 #180

Addresses #160 and #180 

If a category label was blank then it was causing the `CodeList` to not save. This was the cause of both #160 and #180.

The category label inputs were blank when first loading the `CodeList` page as the `categories.json` was being loaded after the `CodeList` form was being displayed. We've addressed this by having the `label` attribute part of the `CodeList` JSON so we now longer get a blank category name.

I've also made it so that if a category name is blank i.e. you make the category name blank in the form for an existing code. Then the save of the `CodeList` will fail and the UI will say `Code list failed to update!`.

As an aside I've refactored the way we were handle updating codes and categories on a code list to use `accepts_nested_attributes_for` so that we have less code and replace it with reliable Rails behaviour.

### CODE REVIEW

**Comment by spuddybike** [comment]
It seems to have failed the checks

**Comment by simonreed** [comment]
Travis doesn't appear to be failing any specific test but instead Travis just appears to be end before it has run all the tests. Very odd, let me take a look. The `browsergroup` branch which has these changes merged into it already runs https://travis-ci.org/CLOSER-Cohorts/archivist/builds/563474173?utm_source=github_status&utm_medium=notification.

**Comment by charlesdebarros** [comment]
I feel recently Travis has been a bit of a hit-and-miss. Simon pushed some changes and Travis was fine with them. Then he pushed some more changes and Travis threw that 'fail' result. And it seems to be an specific test but it does not point out which one that is.

**Comment by simonreed** [comment]
Changed to WIP as I want to test something further.

**Pull request merged**
